version: '2'
services:
  registry:
    restart: always
    image: registry:2.7
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_HEADERS_ACCESS-CONTROL-ALLOW-ORIGIN=['https://${HOSTNAME:?Missing hostname variable}']
    volumes:
      - ./data:/data
      - ./registry-config/:/etc/docker/registry/

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Kerogi's Docker Private Registry
      - REGISTRY_URL=https://${HOSTNAME:?Missing hostname variable}:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
