version: '2'
services:
  registry:
    restart: always
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./conf/registry-srv:/etc/docker/registry:ro
      - ./data:/data

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
    environment:
      - REGISTRY_TITLE=Kerogi's Docker Private Registry
      - REGISTRY_URL=${HOSTNAME:?Missing hostname variable}:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry