version: '2'
services:
  registry:
    restart: always
    image: registry:2.7
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
      - ./registry-config/:/etc/docker/registry/
    networks:
      - registry-ui-net

  ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - REGISTRY_TITLE=Kerogi's Docker Private Registry
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    volumes:
      - ./registry-config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./registry-config/ssl/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - ./registry-config/ssl/key.pem:/etc/nginx/certs/key.pem
    depends_on:
      - registry
    networks:
      - registry-ui-net

networks:
  registry-ui-net: