
version: 0.1

storage:
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true
    
http:
  addr: 0.0.0.0:5000    

auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
#  token:
#    realm: http://localhost:8080/api/auth
#    service: localhost:5000
#    issuer: test
#    rootcertbundle: /etc/docker/registry/auth.cert

log:
  level: info
  
#notifications:
#  endpoints:
#    - name: listener
#      url: http://registry-web:8080/api/notification
#      timeout: 500ms
#      threshold: 5
#      backoff: 1s  

http:
  secret: 9ff83df4f3ab64907f4c2d5cd9dbd3ea3a01a7ed96ed3632f07b6c2ebffcbd36
  tls:
    certificate: /etc/docker/registry/ssl/fullchain.pem
    key: /etc/docker/registry/ssl/key.pem
