version: 0.1

log:
  level: debug


storage:
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true


    
http:
  addr: :5000    
  tls:
    certificate: /etc/docker/registry/ssl/fullchain.pem
    key: /etc/docker/registry/ssl/key.pem
  # headers:
  #   X-Content-Type-Options: [nosniff]
  #   Access-Control-Allow-Origin: []
  #   Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
  #   Access-Control-Allow-Headers: ['Authorization', 'Accept']
  #   Access-Control-Max-Age: [1728000]
  #   Access-Control-Allow-Credentials: [true]
  #   Access-Control-Expose-Headers: ['Docker-Content-Digest']


auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
