version: 0.1

log:
  level: debug


storage:
  filesystem:
    rootdirectory: /data
  delete:
    enabled: true


    
http:
  addr: :5000    
  tls:
    certificate: /etc/docker/registry/ssl/fullchain.pem
    key: /etc/docker/registry/ssl/key.pem

auth:
  htpasswd:
    realm: basic-realm
    path: /etc/docker/registry/htpasswd
